### ISSUE TITLE
[Feature Request]: better control over anime tracking 

### ISSUE THREAD

**Issue by Singout69** [NoCrypt/migu#10]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/NoCrypt/migu#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### Problem Description

Add some extra feature to manually add anime on watchlist or dropped or planning and which episode im at migu only shows i have this anime on my watchlist and for episode i have to scroll down to see at which episode im at and there's no manual way to add episode or rate anything like that i would like if i can finish an series and rate it and be do e with it. 

### Proposed Solution

I mean the feature i asked for dosne't need for explanation but if you don't mind i would recommend checking this page https://github.com/MarshMeadow/Komori
It is a tracking app and not a streaming and it got suspended so you can't find the latest version on play store but there's an apk on their discord server that you can try and maybe implement some ui stuff on migu
https://discord.com/invite/xBnWd6Xd
![Screenshot_2024-08-28-14-00-13-43](https://github.com/user-attachments/assets/f998cb2b-1fa6-4912-a9e7-94261766ec22)

**Comment by NoCrypt** [comment]
Done https://github.com/NoCrypt/migu/commit/50f8c2c1909d11b656c535b2fd3c10fc965b68e9
