### ISSUE TITLE
[Bug]: Anime tracking returning wrong anime

### ISSUE THREAD

**Issue by Hexality** [NoCrypt/migu#44]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/NoCrypt/migu/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/NoCrypt/migu/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/NoCrypt/migu/releases/latest) version of the app.

### What app version are you using?

v5.6.2

### What operating system version are you using?

Linux

### Expected Behavior

Track the anime [Hitoribocchi no Isekai Kouryaku](https://anilist.co/anime/173693/)

![image](https://github.com/user-attachments/assets/56b4b1fd-7c06-429b-a0ba-625463b09bb0)

### Actual Behavior

Returns and tracks an anime called "[Hitoribocchi](https://anilist.co/anime/166056/)" that has nothing to do with the anime that is actually playing.

![image](https://github.com/user-attachments/assets/fcaf9791-d414-4222-97f7-59a05e370879)

### Screenshots

Provided in their respective contexts.

**Comment by NoCrypt** [comment]
Cant reproduce

![image](https://github.com/user-attachments/assets/301f6c9b-8350-4dfd-937e-082ecb328daa)
![image](https://github.com/user-attachments/assets/1f6bdef5-8c05-4329-ae08-4464208f253e)

**Comment by Hexality** [comment]
Maybe cause your is in english(?)

**Comment by Cszyn** [comment]
I've had this with MONOGATARI S2 (Nisemonogatari)  it got turned into Malevolent Spirits: Mononogatari Cour 2

**Comment by Cszyn** [comment]
> I've had this with MONOGATARI S2 (Nisemonogatari) it got turned into Malevolent Spirits: Mononogatari Cour 2

![Migu_8vxPXItwba](https://github.com/user-attachments/assets/2d0c6c64-2aa5-430f-a7d0-762c56a7b509)
